---
sites:
  - name: www
    port: 8000
    domain: www
    services: [www]
  - name: bloge
    port: 8001
    domain: blog
    services: [bloge]
  - name: catsnap
    port: 5000
    domain: catsnap
    services:
      - catsnap
      - catsnap-worker
  - name: identity
    port: 5001
    domain: identity
    services: [identity]
  - name: paste
    port: 7777
    domain: paste
    services: [paste]
  - name: irc
    port: 65431
    domain: irc
    services: []
