---
# packages I figure will be helpful no matter the context
- apt: name=git state=present
- apt: name=libpq-dev state=present
- apt: name=postgresql-client-common state=present
- apt: name=redis-tools state=present

# pip may not be directly needed for deployed apps, but ansible itself
# may need python modules available on deploy targets, so it's nice to
# have it available by default.
- apt: name=python-pip state=present
