---
# packages I figure will be helpful no matter the context
- apt: name={{item}} state=present
  with_items:
    - git
    - libpq-dev
    - postgresql-client-common
    - redis-tools
    - tree

# pip may not be directly needed for deployed apps, but ansible itself
# may need python modules available on deploy targets, so it's nice to
# have it available by default.
- apt: name=python-pip state=present
