---
- include_vars: alorente_ssl_keys.yml
- include_vars: alorente_ssl_certificates.yml

- apt: name={{item}} state=present
  with_items:
    - nginx

- name: ssl certificates
  template: src=ssl_certificate.j2 dest=/etc/ssl/{{item.key}}_andrewlorente_com.chained.crt
            owner=root group=root mode=0444
  with_dict: ssl_certificates
  notify: restart nginx
  no_log: true # these aren't secret, but they're obnoxiously noisy

- name: ssl keys
  template: src=ssl_key.j2 dest=/etc/ssl/{{item.key}}_andrewlorente_com.key owner=root group=root mode=0400
  with_dict: ssl_keys
  notify: restart nginx
  no_log: true

- name: nginx conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf owner=root mode=0444
  notify: restart nginx
